### ISSUE TITLE
Allow other minions to have their attacks copied

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [cheeeeeeeeeen/RoR2-ChensGradiusMod#1]
Beetle Guards and Aurelionite should have their attacks copied as well. Leave the ghosts out.

- [x] Aurelionite
- [x] Beetle Guards
- [x] Squid Polyps

**Comment by cheeeeeeeeeen** [comment]
Aurelionite is now implemented with Options ands full multiplayer sync support.

Beetle guards are next on the list.

**Comment by Coffe-e** [comment]
Are there any plans to add Squid Polyps to this list?
Could be a nice pseudo-buff to the item, but not necessary if it wasn't planned by you.

**Comment by cheeeeeeeeeen** [comment]
Why not? It would be easy too.

**Comment by Coffe-e** [comment]
Oh wow that was fast. Thanks for considering!

**Comment by cheeeeeeeeeen** [comment]
This feature is implemented.
