### ISSUE TITLE
Game crashes with modded survivors

### ISSUE THREAD

**Issue by MightyW0lf** [cheeeeeeeeeen/RoR2-ChensGradiusMod#14]
The game crashes when the mod is installed along any survivor-related* mod. Crash occurs on [game exit](https://youtu.be/o9Mg51iSDqo) or on [starting a run with a modded survivor](https://youtu.be/ppXBmgo13xE).

[LogOutput.log](https://gist.github.com/MightyW0lf/415bc2608f77810b5a5531ce2cb3b885) (with crash after starting a run with Classic Bandit)

\* not sure if *any* survivor-related mod, tested and occurs with (separately):
* Moffein-BanditReloaded-4.0.3
* duckduckgreyduck-ArtificerExtended-3.1.5
* rob-MinerUnearthed-1.5.3

**Comment by cheeeeeeeeeen** [comment]
It's because the current mod version is **bad**. An update is coming to fix this.

**Comment by cheeeeeeeeeen** [comment]
Related issue #13

**Comment by cheeeeeeeeeen** [comment]
Issue #13 fixed, so this is also fixed.
