### ISSUE TITLE
None of the Gradius items are showing up

### ISSUE THREAD

**Issue by Zenji01** [cheeeeeeeeeen/RoR2-ChensGradiusMod#21]
Seems like after the update that came out today removed the items from being selected being the Gradius red item and the new green item. Just thought I'd let you know

**Comment by cheeeeeeeeeen** [comment]
Log would be really helpful.

**Comment by cheeeeeeeeeen** [comment]
But I would assume it has something to do with TILER2 needing an update.

**Comment by cheeeeeeeeeen** [comment]
I just tested a normal playthrough. The item shows up as normally in command droplets.

**Comment by cheeeeeeeeeen** [comment]
@Zenji01 Re-open the issue once you can send a log and comment again. Thanks.

**Comment by Zenji01** [comment]
Would that be the logOutput?

**Comment by cheeeeeeeeeen** [comment]
Yes.

**Comment by cheeeeeeeeeen** [comment]
If you started another run already, then it's wiped out. Please recreate the issue by then so that the log will display the errors.

**Comment by Zenji01** [comment]
Alright I've got a lot of mods and I haven't started a new run or anything I'll be posting the log now

**Comment by Zenji01** [comment]
[LogOutput.log](https://github.com/cheeeeeeeeeen/RoR2-ChensGradiusMod/files/6603254/LogOutput.log)

**Comment by cheeeeeeeeeen** [comment]
```
[Error : BepInEx] Could not load [ChensGradiusMod 3.2.0] because it has missing dependencies: com.ThinkInvisible.TILER2 (v4.0.7 or newer), com.Chen.ChensHelpers (v1.0.10 or newer)
```

There you have it. Not a bug then.
