### ISSUE TITLE
Gradius' Option Seed causes endless Blast Canister firing on MUL-T

### ISSUE THREAD

**Issue by PugLyf** [cheeeeeeeeeen/RoR2-ChensGradiusMod#23]
### Describe the Bug
When playing MUL-T on obtaining a Gradius' Option Seed and firing Blast Canister the ability is rapid fired endlessly.

### To Reproduce
1. Play MUL-T
2. Obtain the item Gradius' Option Seed
3. Fire Blast Canister (RMB)

### Expected Behavior
From my understanding, based on the item description, 2 extra versions of the projectile fired from the ability should spawn.

### Console Log

[LogOutput.log](https://github.com/cheeeeeeeeeen/RoR2-ChensGradiusMod/files/6683465/LogOutput.log)

### Additional Context

This is a screenshot of what the bug looks like.
![632360_20210620190251_1](https://user-images.githubusercontent.com/28744016/122694869-0e7d7980-d1fc-11eb-9f74-499cf6ba8810.png)

**Comment by cheeeeeeeeeen** [comment]
I'm trying to look into this problem. So far 3 people have this.

**Comment by cheeeeeeeeeen** [comment]
https://discord.com/channels/562704639141740588/562711077453037589/856335055441100850

**Comment by cheeeeeeeeeen** [comment]
https://discord.com/channels/562704639141740588/562711077453037589/856194160368943104

**Comment by cheeeeeeeeeen** [comment]
@PugLyf Can you share your profile?

**Comment by cheeeeeeeeeen** [comment]
Should be fixed in 3.3.8
