### ISSUE TITLE
Gradius' Option Seed significantly buffs Leeching Seed, Harvester's Scythe, and Brilliant Behemoth on TR58 Carbonizer Turrets

### ISSUE THREAD

**Issue by CanvasK** [cheeeeeeeeeen/RoR2-ChensGradiusMod#27]
### Describe the Bug
Using Gradius' Option Seed with Engineer's TR58 Carbonizer Turrets (mobile turrets) will cause the duplicated attacks to give around 25x more health when using Leeching Seed (screenshot 1) or Harvester's Scythe (screenshot 2) and the explosion from Brilliant Behemoth is significantly larger (screenshot 3 & 4) at an estimated 60m. This does not occur with the TR12 Gauss Auto-Turret (stationary turrets).

### To Reproduce
1. Play Engineer
2. Obtain Gradius' Option Seed
3. Obtain Leeching Seed, Harvester's Scythe, or Brilliant Behemoth
4. Spawn a TR58 Carbonizer Turret
5. Let it attack

### Expected Behavior
Leeching Seed should only heal 0.6 HP (rounded to 1 HP in display). Harvester's Scythe should only heal 4.8 HP (rounded to 5 HP in display). Brilliant Behemoth explosions should only be around 4m in radius.

### Console Log
[LogOutput.log](https://github.com/cheeeeeeeeeen/RoR2-ChensGradiusMod/files/7346819/LogOutput.log)

### Additional Context
Other mods are active but they are mostly QoL. Has been replicated with only the Gradius and DebugToolkit (for testing) mods being enabled.
Screenshots showing the issues:
Harvester's Scythe
![Screenshot_473](https://user-images.githubusercontent.com/39473337/137338913-85fd3920-8648-4e0e-b235-0ff5874ca72c.png)
Leeching Seed
![Screenshot_475](https://user-images.githubusercontent.com/39473337/137338959-2133efc4-1f07-4ec5-9cc9-466682dd52e4.png)
Brilliant Behemoth
![Screenshot_474](https://user-images.githubusercontent.com/39473337/137338982-ced3b500-3a6f-4221-828c-1a69f7aab904.png)
Brilliant Behemoth. HitboxViewerMod (by TheTimesweeper) enabled and taken with PhotoMode (by CWMlolzlz) with 40 Bustling Fungus (~62m radius) to estimate size
![Screenshot_476](https://user-images.githubusercontent.com/39473337/137342785-f2fad85d-34fa-47fb-a7ce-cde7ed785544.png)

**Comment by cheeeeeeeeeen** [comment]
I still do not know what causes t his behaviour. There might be a bad computation somewhere, or an uncaught case. All damage done in code is multiplied accordingly.

**Comment by cheeeeeeeeeen** [comment]
@CanvasK I finally solved the problem! It was a minor mistake but a hard one to detect.

https://i.imgur.com/hwEYkh5.gif
