### ISSUE TITLE
Classic Items: Artifact of Origin

### ISSUE THREAD

**Issue by ashleywest21** [cheeeeeeeeeen/RoR2-ChensGradiusMod#3]
Every 10 minutes, an imp overlord(potentially renamed to "Imp Vanguard") and three regular imps will enter the map. The Vengeance screen effect will occur as well until they are defeated. The Overlord has a red item and uses it. The regular imps have green items(one each) that they also make use of. These items are dropped when their respective holder is slain. The Overlord counts as a boss and will have its health bar displayed prominently on the screen. Armor piercing rounds will deal bonus damage, as is the case normally for bosses.

**Comment by cheeeeeeeeeen** [comment]
Recreated issue in the correct repo. Thanks!
