### ISSUE TITLE
Psy Drone + Dronemeld

### ISSUE THREAD

**Issue by airwickfan** [cheeeeeeeeeen/RoR2-ChensGradiusMod#37]
Hi, I've added "PsyDroneMaster" and "DronePsyMaster" to the master whitelist for the Dronemeld config file in an attempt to configure Psy drone's to stack with the Dronemeld mod, but I was unable to get it to work for Psy drones from the ChensGradiusMod. It works properly with all other drones from Chen's mods. Is it under a different code name? Please help, thanks.

**Comment by cheeeeeeeeeen** [comment]
It is PsyDroneRedMaster and PsyDroneGreenMaster
