### ISSUE TITLE
Void fiend has no interaction with the Gradius Option seed

### ISSUE THREAD

**Issue by LewdLemons** [cheeeeeeeeeen/RoR2-ChensGradiusMod#38]
### Console Log
**Please include a link or embed of a FULL console log file from a run of the game where the bug happened**. This will provide a versioned mod list, and possibly other important information about the bug.

*To retrieve console logs:* A log from the most recent run of the game will be stored in `.../Risk of Rain 2/BepInEx/LogOutput.log`. If using r2modman, go to Settings > Browse profile folder > `Profile Folder/BepInEx/LogOutput.log` instead.

*If the bug only happens in multiplayer:* try to provide console logs from both client and server.

*If the log file is too big to post:* this may be because of a once-per-frame error message. In this case, immediately close the game once the bug occurs to reduce log file size.

### Additional Context
Add any other context about the problem here (screenshots, etc.).

**Comment by cheeeeeeeeeen** [comment]
#41 solved this.
